#!/bin/bash

# This script is designed to run on system wake-up to fix color issues
# by toggling the HDR setting off and on.

CONNECTED_OUTPUT=eDP-1

if [ -n "$CONNECTED_OUTPUT" ]; then
    kscreen-doctor output."$CONNECTED_OUTPUT".hdr.disable
    # sleep 1
    kscreen-doctor output."$CONNECTED_OUTPUT".hdr.enable
fi
